"""add reference to project in task

Revision ID: 2c84c4ad5b68
Revises: c21dd0bc2c85
Create Date: 2024-07-22 15:28:45.628332

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c84c4ad5b68"
down_revision: str | None = "c21dd0bc2c85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_project_id", "project", ["project_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_constraint("fk_project_id", type_="foreignkey")
        batch_op.drop_column("project_id")

    # ### end Alembic commands ###
