"""add project

Revision ID: c5254dc6083f
Revises: bf86033947fc
Create Date: 2024-07-16 09:09:46.661274

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5254dc6083f"
down_revision: str | None = "bf86033947fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name",sa.String(255), nullable=False),
        sa.Column("model_card", sa.String(255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project")
    # ### end Alembic commands ###
