"""Add the publish model

Revision ID: c76fb66f2c4d
Revises: cda3a7384ce8
Create Date: 2025-11-07 16:40:02.788637

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c76fb66f2c4d"
down_revision: str | None = "cda3a7384ce8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_code", sa.String(length=255), nullable=False),
        sa.Column(
            "publication_status",
            postgresql.ENUM(
                "STATE_1", "STATE_2", "PUBLISHED", name="publication_status"
            ),
            nullable=True,
        ),
        sa.Column("publication_link", sa.String(length=255), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("lars", sa.String(length=8), nullable=True),
        sa.Column("algorithm_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["algorithm_id"],
            ["algorithm.id"],
            name=op.f("fk_publication_algorithm_id_algorithm"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication")),
        sa.UniqueConstraint("algorithm_id", name=op.f("uq_publication_algorithm_id")),
    )
    op.create_index(op.f("ix_publication_lars"), "publication", ["lars"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_publication_lars"), table_name="publication")
    op.drop_table("publication")
    postgresql.ENUM(name="publication_status").drop(op.get_bind(), checkfirst=True)
