"""authorization system

Revision ID: e16bb3d53cd6
Revises: 5de977ad946f
Create Date: 2024-12-23 08:32:15.194858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from amt.core.authorization import AuthorizationResource, AuthorizationVerb

# revision identifiers, used by Alembic.
revision: str = "e16bb3d53cd6"
down_revision: str | None = "5de977ad946f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_table = op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    rule_table = op.create_table(
        "rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("verbs", sa.JSON(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_rule_role_id_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule")),
    )

    authorization_table = op.create_table(
        "authorization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_authorization_role_id_role")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_authorization_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authorization")),
    )


    op.bulk_insert(
        role_table,
        [
            {'id': 1, 'name': 'Organization Maintainer'},
            {'id': 2, 'name': 'Organization Member'},
            {'id': 3, 'name': 'Organization Viewer'},
            {'id': 4, 'name': 'Algorithm Maintainer'},
            {'id': 5, 'name': 'Algorithm Member'},
            {'id': 6, 'name': 'Algorithm Viewer'},
        ]
    )

    op.bulk_insert(
        rule_table,
        [
            {'id': 1, 'resource': AuthorizationResource.ORGANIZATION_INFO, 'verbs': [AuthorizationVerb.CREATE, AuthorizationVerb.READ, AuthorizationVerb.UPDATE, AuthorizationVerb.DELETE], 'role_id': 1},
        ]
    )

    op.bulk_insert(
        authorization_table,
        [
        ]
    )


def downgrade() -> None:
    op.drop_table("rule")
    op.drop_table("authorization")
    op.drop_table("role")

