"""remove project table

Revision ID: f6da4d6dd867
Revises: ff46b7ecc348
Create Date: 2024-11-15 11:30:25.352543

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "f6da4d6dd867"
down_revision: str | None = "ff46b7ecc348"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("lifecycle", sa.VARCHAR(length=32), nullable=True),
        sa.Column("last_edited", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("system_card_json", sqlite.JSON(), nullable=True),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_project"),
    )
    # ### end Alembic commands ###
