default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^amt/static/vendor/.*
      - id: trailing-whitespace
      - id: check-yaml
        exclude: example/
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: check-modified-migrations
        name: check-modified-migrations
        entry: sh -c '! git diff --cached --name-only --diff-filter=MD | grep ^amt/migrations/versions'
        language: system
        pass_filenames: false
        always_run: true
ci:
  autofix_prs: false
  autofix_commit_msg: "Auto fix pre-commit.com hooks"
  autoupdate_commit_msg: "Update .pre-commit-config.yaml"
