default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: "^amt/static/vendor/.*|amt/locale/.*"
      - id: trailing-whitespace
      - id: check-yaml
        exclude: "^(example|example_system_card|example_registry)/"
      - id: check-json
        exclude: 'tsconfig\.json'
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--config, pyproject.toml]
      - id: ruff-format
        args: [--config, pyproject.toml]
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-jinja
  - repo: local
    hooks:
      - id: check-modified-migrations
        name: check-modified-migrations
        entry: sh -c '! git diff --cached --name-only --diff-filter=MD | grep ^amt/migrations/versions'
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: check-translate
        name: check-translate
        additional_dependencies: [polib]
        entry: ./script/check_translate
        language: python
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: check-translate-compiled
        name: check-translate-compiled
        entry: ./script/check_compiled_translations
        language: system
        files: \.po$
  - repo: local
    hooks:
      - id: po-file-handler
        name: PO file timestamp homogenizer
        entry: ./script/po_file_handler
        language: python
        files: \.(po|pot)$
        stages: [pre-commit]
        additional_dependencies: ["babel==2.15.0"] # Specify the version you need
  - repo: local
    hooks:
      - id: husky-run-pre-commit-lint
        name: husky-lint
        language: system
        entry: .husky/pre-commit-lint
        pass_filenames: false
        always_run: true
      - id: husky-run-pre-commit-prettier
        name: husky-prettier
        language: system
        entry: .husky/pre-commit-prettier
        pass_filenames: false
        always_run: true
ci:
  autofix_prs: false
  autofix_commit_msg: "Auto fix pre-commit.com hooks"
  autoupdate_commit_msg: "Update .pre-commit-config.yaml"
  skip: [husky-run-pre-commit-lint, husky-run-pre-commit-prettier]
