services:
  tad:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/minbzk/tad:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable not set}
    ports:
      - 8000:8000

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./database/:/docker-entrypoint-initdb.d/:cached
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable not set}
      - SECRET_KEY=${SECRET_KEY:?Variable not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "tad", "-U", "postgres"]
      start_period: 10s


  db-admin:
    image: dpage/pgadmin4:8.6
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-berry.hartog@minbzk.nl}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:?Variable not set}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT:-8080}
    depends_on:
      db:
        condition: service_healthy


#TODO(berry): Traefik

volumes:
  app-db-data:
