services:
  tad:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/minbzk/tad:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - path: .env
        required: true
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable not set}
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/live || exit 1"]

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - ./database/:/docker-entrypoint-initdb.d/:cached
    env_file:
      - path: .env
        required: true
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Variable not set}
      - SECRET_KEY=${SECRET_KEY:?Variable not set}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "tad", "-U", "tad"]
      start_period: 3s


  db-admin:
    image: dpage/pgadmin4:8.6
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-tad@minbzk.nl}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:?Variable not set}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT:-8080}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:8080/misc/ping"]


#TODO(berry): Traefik

volumes:
  app-db-data:
