# coding: utf-8

# flake8: noqa
"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.algorithm_action_response import (
    AlgorithmActionResponse,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.algorithm_in import AlgorithmIn
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.algorithm_summary import AlgorithmSummary
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.any_of_the_algorithm_standards import (
    AnyOfTheAlgorithmStandards,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.archive_version_request import (
    ArchiveVersionRequest,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.http_validation_error import HTTPValidationError
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.language import Language
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.message import Message
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.new_algorithm_response import NewAlgorithmResponse
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.preview_url import PreviewUrl
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.state import State
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v01_algorithm import V01Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v01_enum_standard_version import (
    V01EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_algorithm import V023Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_dpia import V023EnumDpia
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_iama import V023EnumIama
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_mprd import V023EnumMprd
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_standard_version import (
    V023EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_status import V023EnumStatus
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_type import V023EnumType
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_algorithm import V031Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_dpia import V031EnumDpia
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_iama import V031EnumIama
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_standard_version import (
    V031EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_status import V031EnumStatus
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_type import V031EnumType
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_algorithm import V04Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_category import V04EnumCategory
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_standard_version import (
    V04EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_status import V04EnumStatus
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_type import V04EnumType
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_algorithm import V10Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_category import V10EnumCategory
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_lang import V10EnumLang
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_publication_category import (
    V10EnumPublicationCategory,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_standard_version import (
    V10EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_status import V10EnumStatus
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_object_impacttoetsen_grouping import (
    V10ObjectImpacttoetsenGrouping,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_object_lawful_basis_grouping import (
    V10ObjectLawfulBasisGrouping,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_object_source_data_grouping import (
    V10ObjectSourceDataGrouping,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.validation_error import ValidationError
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.validation_error_loc_inner import (
    ValidationErrorLocInner,
)
