# coding: utf-8

"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class AlgorithmSummary(BaseModel):
    """
    AlgorithmSummary
    """  # noqa: E501

    name: Optional[StrictStr] = None
    schema_version: Optional[StrictStr] = None
    last_update_dt: datetime
    lars: StrictStr
    source_id: Optional[StrictStr] = None
    published: StrictBool
    current_version_released: StrictBool
    current_version_published: StrictBool
    last_update_by: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "schema_version",
        "last_update_dt",
        "lars",
        "source_id",
        "published",
        "current_version_released",
        "current_version_published",
        "last_update_by",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlgorithmSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict["name"] = None

        # set to None if schema_version (nullable) is None
        # and model_fields_set contains the field
        if self.schema_version is None and "schema_version" in self.model_fields_set:
            _dict["schema_version"] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict["source_id"] = None

        # set to None if last_update_by (nullable) is None
        # and model_fields_set contains the field
        if self.last_update_by is None and "last_update_by" in self.model_fields_set:
            _dict["last_update_by"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlgorithmSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "schema_version": obj.get("schema_version"),
                "last_update_dt": obj.get("last_update_dt"),
                "lars": obj.get("lars"),
                "source_id": obj.get("source_id"),
                "published": obj.get("published"),
                "current_version_released": obj.get("current_version_released"),
                "current_version_published": obj.get("current_version_published"),
                "last_update_by": obj.get("last_update_by"),
            }
        )
        return _obj
