# coding: utf-8

"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v01_algorithm import V01Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_algorithm import V023Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_algorithm import V031Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_algorithm import V04Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_algorithm import V10Algorithm
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

ANYOFTHEALGORITHMSTANDARDS_ANY_OF_SCHEMAS = [
    "V01Algorithm",
    "V023Algorithm",
    "V031Algorithm",
    "V04Algorithm",
    "V10Algorithm",
]


class AnyOfTheAlgorithmStandards(BaseModel):
    """
    AnyOfTheAlgorithmStandards
    """

    # data type: V031Algorithm
    anyof_schema_1_validator: Optional[V031Algorithm] = None
    # data type: V01Algorithm
    anyof_schema_2_validator: Optional[V01Algorithm] = None
    # data type: V023Algorithm
    anyof_schema_3_validator: Optional[V023Algorithm] = None
    # data type: V04Algorithm
    anyof_schema_4_validator: Optional[V04Algorithm] = None
    # data type: V10Algorithm
    anyof_schema_5_validator: Optional[V10Algorithm] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[V01Algorithm, V023Algorithm, V031Algorithm, V04Algorithm, V10Algorithm]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = {"V01Algorithm", "V023Algorithm", "V031Algorithm", "V04Algorithm", "V10Algorithm"}

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_anyof(cls, v):
        if v is None:
            return v

        instance = AnyOfTheAlgorithmStandards.model_construct()
        error_messages = []
        # validate data type: V031Algorithm
        if not isinstance(v, V031Algorithm):
            error_messages.append(f"Error! Input type `{type(v)}` is not `V031Algorithm`")
        else:
            return v

        # validate data type: V01Algorithm
        if not isinstance(v, V01Algorithm):
            error_messages.append(f"Error! Input type `{type(v)}` is not `V01Algorithm`")
        else:
            return v

        # validate data type: V023Algorithm
        if not isinstance(v, V023Algorithm):
            error_messages.append(f"Error! Input type `{type(v)}` is not `V023Algorithm`")
        else:
            return v

        # validate data type: V04Algorithm
        if not isinstance(v, V04Algorithm):
            error_messages.append(f"Error! Input type `{type(v)}` is not `V04Algorithm`")
        else:
            return v

        # validate data type: V10Algorithm
        if not isinstance(v, V10Algorithm):
            error_messages.append(f"Error! Input type `{type(v)}` is not `V10Algorithm`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError(
                "No match found when setting the actual_instance in AnyOfTheAlgorithmStandards with anyOf schemas: V01Algorithm, V023Algorithm, V031Algorithm, V04Algorithm, V10Algorithm. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        if json_str is None:
            return instance

        error_messages = []
        # anyof_schema_1_validator: Optional[V031Algorithm] = None
        try:
            instance.actual_instance = V031Algorithm.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[V01Algorithm] = None
        try:
            instance.actual_instance = V01Algorithm.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[V023Algorithm] = None
        try:
            instance.actual_instance = V023Algorithm.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[V04Algorithm] = None
        try:
            instance.actual_instance = V04Algorithm.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[V10Algorithm] = None
        try:
            instance.actual_instance = V10Algorithm.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into AnyOfTheAlgorithmStandards with anyOf schemas: V01Algorithm, V023Algorithm, V031Algorithm, V04Algorithm, V10Algorithm. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[Union[Dict[str, Any], V01Algorithm, V023Algorithm, V031Algorithm, V04Algorithm, V10Algorithm]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
