# coding: utf-8

"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class State(str, Enum):
    """
    An arbitrary number of states to be used by flows. An old version of an algorithm version has status EXPIRED. Meaning only the newest versions have STATE_X and other versions always have PUBLISHED / EXPIRED / ARCHIVED.
    """

    """
    allowed enum values
    """
    STATE_1 = "STATE_1"
    STATE_2 = "STATE_2"
    PUBLISHED = "PUBLISHED"
    EXPIRED = "EXPIRED"
    ARCHIVED = "ARCHIVED"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of State from a JSON string"""
        return cls(json.loads(json_str))
