# coding: utf-8

"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.language import Language
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.state import State
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_dpia import V031EnumDpia
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_iama import V031EnumIama
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_standard_version import (
    V031EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_status import V031EnumStatus
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_type import V031EnumType
from typing import Optional, Set
from typing_extensions import Self


class V031Algorithm(BaseModel):
    """
    V031Algorithm
    """  # noqa: E501

    name: StrictStr
    organization: StrictStr
    department: Optional[StrictStr] = None
    description_short: Optional[StrictStr] = None
    type: Optional[V031EnumType] = None
    category: Optional[StrictStr] = None
    website: Optional[StrictStr] = None
    status: Optional[V031EnumStatus] = None
    goal: Optional[StrictStr] = None
    impact: Optional[StrictStr] = None
    proportionality: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    application_url: Optional[StrictStr] = None
    process_index_url: Optional[StrictStr] = None
    lawful_basis: Optional[StrictStr] = None
    iama: Optional[V031EnumIama] = None
    iama_description: Optional[StrictStr] = None
    dpia: Optional[V031EnumDpia] = None
    objection_procedure: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    contact_email: Optional[StrictStr] = None
    area: Optional[StrictStr] = None
    lang: Optional[StrictStr] = None
    standard_version: Optional[V031EnumStandardVersion] = None
    uuid: Optional[StrictStr] = None
    source_id: Optional[StrictStr] = None
    revision_date: Optional[StrictStr] = None
    tags: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    source_data: Optional[StrictStr] = None
    methods_and_models: Optional[StrictStr] = None
    publiccode: Optional[StrictStr] = None
    monitoring: Optional[StrictStr] = None
    human_intervention: Optional[StrictStr] = None
    risks: Optional[StrictStr] = None
    performance_standard: Optional[StrictStr] = None
    lars: StrictStr
    publication_dt: Optional[StrictStr] = None
    create_dt: datetime
    language: Language
    state: State
    __properties: ClassVar[List[str]] = [
        "name",
        "organization",
        "department",
        "description_short",
        "type",
        "category",
        "website",
        "status",
        "goal",
        "impact",
        "proportionality",
        "provider",
        "application_url",
        "process_index_url",
        "lawful_basis",
        "iama",
        "iama_description",
        "dpia",
        "objection_procedure",
        "url",
        "contact_email",
        "area",
        "lang",
        "standard_version",
        "uuid",
        "source_id",
        "revision_date",
        "tags",
        "description",
        "source_data",
        "methods_and_models",
        "publiccode",
        "monitoring",
        "human_intervention",
        "risks",
        "performance_standard",
        "lars",
        "publication_dt",
        "create_dt",
        "language",
        "state",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V031Algorithm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if department (nullable) is None
        # and model_fields_set contains the field
        if self.department is None and "department" in self.model_fields_set:
            _dict["department"] = None

        # set to None if description_short (nullable) is None
        # and model_fields_set contains the field
        if self.description_short is None and "description_short" in self.model_fields_set:
            _dict["description_short"] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict["type"] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict["category"] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict["website"] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict["status"] = None

        # set to None if goal (nullable) is None
        # and model_fields_set contains the field
        if self.goal is None and "goal" in self.model_fields_set:
            _dict["goal"] = None

        # set to None if impact (nullable) is None
        # and model_fields_set contains the field
        if self.impact is None and "impact" in self.model_fields_set:
            _dict["impact"] = None

        # set to None if proportionality (nullable) is None
        # and model_fields_set contains the field
        if self.proportionality is None and "proportionality" in self.model_fields_set:
            _dict["proportionality"] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict["provider"] = None

        # set to None if application_url (nullable) is None
        # and model_fields_set contains the field
        if self.application_url is None and "application_url" in self.model_fields_set:
            _dict["application_url"] = None

        # set to None if process_index_url (nullable) is None
        # and model_fields_set contains the field
        if self.process_index_url is None and "process_index_url" in self.model_fields_set:
            _dict["process_index_url"] = None

        # set to None if lawful_basis (nullable) is None
        # and model_fields_set contains the field
        if self.lawful_basis is None and "lawful_basis" in self.model_fields_set:
            _dict["lawful_basis"] = None

        # set to None if iama (nullable) is None
        # and model_fields_set contains the field
        if self.iama is None and "iama" in self.model_fields_set:
            _dict["iama"] = None

        # set to None if iama_description (nullable) is None
        # and model_fields_set contains the field
        if self.iama_description is None and "iama_description" in self.model_fields_set:
            _dict["iama_description"] = None

        # set to None if dpia (nullable) is None
        # and model_fields_set contains the field
        if self.dpia is None and "dpia" in self.model_fields_set:
            _dict["dpia"] = None

        # set to None if objection_procedure (nullable) is None
        # and model_fields_set contains the field
        if self.objection_procedure is None and "objection_procedure" in self.model_fields_set:
            _dict["objection_procedure"] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict["url"] = None

        # set to None if contact_email (nullable) is None
        # and model_fields_set contains the field
        if self.contact_email is None and "contact_email" in self.model_fields_set:
            _dict["contact_email"] = None

        # set to None if area (nullable) is None
        # and model_fields_set contains the field
        if self.area is None and "area" in self.model_fields_set:
            _dict["area"] = None

        # set to None if lang (nullable) is None
        # and model_fields_set contains the field
        if self.lang is None and "lang" in self.model_fields_set:
            _dict["lang"] = None

        # set to None if standard_version (nullable) is None
        # and model_fields_set contains the field
        if self.standard_version is None and "standard_version" in self.model_fields_set:
            _dict["standard_version"] = None

        # set to None if uuid (nullable) is None
        # and model_fields_set contains the field
        if self.uuid is None and "uuid" in self.model_fields_set:
            _dict["uuid"] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict["source_id"] = None

        # set to None if revision_date (nullable) is None
        # and model_fields_set contains the field
        if self.revision_date is None and "revision_date" in self.model_fields_set:
            _dict["revision_date"] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if source_data (nullable) is None
        # and model_fields_set contains the field
        if self.source_data is None and "source_data" in self.model_fields_set:
            _dict["source_data"] = None

        # set to None if methods_and_models (nullable) is None
        # and model_fields_set contains the field
        if self.methods_and_models is None and "methods_and_models" in self.model_fields_set:
            _dict["methods_and_models"] = None

        # set to None if publiccode (nullable) is None
        # and model_fields_set contains the field
        if self.publiccode is None and "publiccode" in self.model_fields_set:
            _dict["publiccode"] = None

        # set to None if monitoring (nullable) is None
        # and model_fields_set contains the field
        if self.monitoring is None and "monitoring" in self.model_fields_set:
            _dict["monitoring"] = None

        # set to None if human_intervention (nullable) is None
        # and model_fields_set contains the field
        if self.human_intervention is None and "human_intervention" in self.model_fields_set:
            _dict["human_intervention"] = None

        # set to None if risks (nullable) is None
        # and model_fields_set contains the field
        if self.risks is None and "risks" in self.model_fields_set:
            _dict["risks"] = None

        # set to None if performance_standard (nullable) is None
        # and model_fields_set contains the field
        if self.performance_standard is None and "performance_standard" in self.model_fields_set:
            _dict["performance_standard"] = None

        # set to None if publication_dt (nullable) is None
        # and model_fields_set contains the field
        if self.publication_dt is None and "publication_dt" in self.model_fields_set:
            _dict["publication_dt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V031Algorithm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "organization": obj.get("organization"),
                "department": obj.get("department"),
                "description_short": obj.get("description_short"),
                "type": obj.get("type"),
                "category": obj.get("category"),
                "website": obj.get("website"),
                "status": obj.get("status"),
                "goal": obj.get("goal"),
                "impact": obj.get("impact"),
                "proportionality": obj.get("proportionality"),
                "provider": obj.get("provider"),
                "application_url": obj.get("application_url"),
                "process_index_url": obj.get("process_index_url"),
                "lawful_basis": obj.get("lawful_basis"),
                "iama": obj.get("iama"),
                "iama_description": obj.get("iama_description"),
                "dpia": obj.get("dpia"),
                "objection_procedure": obj.get("objection_procedure"),
                "url": obj.get("url"),
                "contact_email": obj.get("contact_email"),
                "area": obj.get("area"),
                "lang": obj.get("lang"),
                "standard_version": obj.get("standard_version"),
                "uuid": obj.get("uuid"),
                "source_id": obj.get("source_id"),
                "revision_date": obj.get("revision_date"),
                "tags": obj.get("tags"),
                "description": obj.get("description"),
                "source_data": obj.get("source_data"),
                "methods_and_models": obj.get("methods_and_models"),
                "publiccode": obj.get("publiccode"),
                "monitoring": obj.get("monitoring"),
                "human_intervention": obj.get("human_intervention"),
                "risks": obj.get("risks"),
                "performance_standard": obj.get("performance_standard"),
                "lars": obj.get("lars"),
                "publication_dt": obj.get("publication_dt"),
                "create_dt": obj.get("create_dt"),
                "language": obj.get("language"),
                "state": obj.get("state"),
            }
        )
        return _obj
