# coding: utf-8

"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class V04EnumCategory(str, Enum):
    """
    V04EnumCategory
    """

    """
    allowed enum values
    """
    ORGANISATIE_EN_BEDRIJFSVOERING = "Organisatie en bedrijfsvoering"
    DIENSTVERLENING = "Dienstverlening"
    BESTUUR = "Bestuur"
    CULTUUR_EN_RECREATIE = "Cultuur en recreatie"
    ECONOMIE = "Economie"
    FINANCIËN = "Financiën"
    HUISVESTING = "Huisvesting"
    INTERNATIONAAL = "Internationaal"
    LANDBOUW = "Landbouw"
    MIGRATIE_EN_INTEGRATIE = "Migratie en integratie"
    NATUUR_EN_MILIEU = "Natuur en milieu"
    ONDERWIJS_EN_WETENSCHAP = "Onderwijs en wetenschap"
    OPENBARE_ORDE_EN_VEILIGHEID = "Openbare orde en veiligheid"
    RECHT = "Recht"
    RUIMTE_EN_INFRASTRUCTUUR = "Ruimte en infrastructuur"
    SOCIALE_ZEKERHEID = "Sociale zekerheid"
    VERKEER = "Verkeer"
    WERK = "Werk"
    ZORG_EN_GEZONDHEID = "Zorg en gezondheid"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of V04EnumCategory from a JSON string"""
        return cls(json.loads(json_str))
