# coding: utf-8

"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.language import Language
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.state import State
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_lang import V10EnumLang
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_publication_category import (
    V10EnumPublicationCategory,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_standard_version import (
    V10EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_status import V10EnumStatus
from typing import Optional, Set
from typing_extensions import Self


class V10Algorithm(BaseModel):
    """
    V10Algorithm
    """  # noqa: E501

    name: StrictStr
    description_short: StrictStr
    organization: StrictStr
    category: Optional[List[Any]] = None
    status: V10EnumStatus
    begin_date: Optional[StrictStr] = None
    end_date: Optional[StrictStr] = None
    contact_email: StrictStr
    website: Optional[StrictStr] = None
    publication_category: V10EnumPublicationCategory
    url: Optional[StrictStr] = None
    goal: Optional[StrictStr] = None
    proportionality: Optional[StrictStr] = None
    human_intervention: Optional[StrictStr] = None
    risks: Optional[StrictStr] = None
    lawful_basis: Optional[StrictStr] = None
    lawful_basis_grouping: Optional[List[Any]] = None
    process_index_url: Optional[StrictStr] = None
    impacttoetsen_grouping: Optional[List[Any]] = None
    impacttoetsen: Optional[StrictStr] = None
    source_data: Optional[StrictStr] = None
    source_data_grouping: Optional[List[Any]] = None
    methods_and_models: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    publiccode: Optional[StrictStr] = None
    lang: V10EnumLang
    standard_version: Optional[V10EnumStandardVersion] = None
    source_id: Optional[StrictStr] = None
    tags: Optional[StrictStr] = None
    lars: StrictStr
    publication_dt: Optional[StrictStr] = None
    create_dt: datetime
    language: Language
    state: State
    __properties: ClassVar[List[str]] = [
        "name",
        "description_short",
        "organization",
        "category",
        "status",
        "begin_date",
        "end_date",
        "contact_email",
        "website",
        "publication_category",
        "url",
        "goal",
        "proportionality",
        "human_intervention",
        "risks",
        "lawful_basis",
        "lawful_basis_grouping",
        "process_index_url",
        "impacttoetsen_grouping",
        "impacttoetsen",
        "source_data",
        "source_data_grouping",
        "methods_and_models",
        "provider",
        "publiccode",
        "lang",
        "standard_version",
        "source_id",
        "tags",
        "lars",
        "publication_dt",
        "create_dt",
        "language",
        "state",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V10Algorithm from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if begin_date (nullable) is None
        # and model_fields_set contains the field
        if self.begin_date is None and "begin_date" in self.model_fields_set:
            _dict["begin_date"] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict["end_date"] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict["website"] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict["url"] = None

        # set to None if goal (nullable) is None
        # and model_fields_set contains the field
        if self.goal is None and "goal" in self.model_fields_set:
            _dict["goal"] = None

        # set to None if proportionality (nullable) is None
        # and model_fields_set contains the field
        if self.proportionality is None and "proportionality" in self.model_fields_set:
            _dict["proportionality"] = None

        # set to None if human_intervention (nullable) is None
        # and model_fields_set contains the field
        if self.human_intervention is None and "human_intervention" in self.model_fields_set:
            _dict["human_intervention"] = None

        # set to None if risks (nullable) is None
        # and model_fields_set contains the field
        if self.risks is None and "risks" in self.model_fields_set:
            _dict["risks"] = None

        # set to None if lawful_basis (nullable) is None
        # and model_fields_set contains the field
        if self.lawful_basis is None and "lawful_basis" in self.model_fields_set:
            _dict["lawful_basis"] = None

        # set to None if process_index_url (nullable) is None
        # and model_fields_set contains the field
        if self.process_index_url is None and "process_index_url" in self.model_fields_set:
            _dict["process_index_url"] = None

        # set to None if impacttoetsen (nullable) is None
        # and model_fields_set contains the field
        if self.impacttoetsen is None and "impacttoetsen" in self.model_fields_set:
            _dict["impacttoetsen"] = None

        # set to None if source_data (nullable) is None
        # and model_fields_set contains the field
        if self.source_data is None and "source_data" in self.model_fields_set:
            _dict["source_data"] = None

        # set to None if methods_and_models (nullable) is None
        # and model_fields_set contains the field
        if self.methods_and_models is None and "methods_and_models" in self.model_fields_set:
            _dict["methods_and_models"] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict["provider"] = None

        # set to None if publiccode (nullable) is None
        # and model_fields_set contains the field
        if self.publiccode is None and "publiccode" in self.model_fields_set:
            _dict["publiccode"] = None

        # set to None if standard_version (nullable) is None
        # and model_fields_set contains the field
        if self.standard_version is None and "standard_version" in self.model_fields_set:
            _dict["standard_version"] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict["source_id"] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if publication_dt (nullable) is None
        # and model_fields_set contains the field
        if self.publication_dt is None and "publication_dt" in self.model_fields_set:
            _dict["publication_dt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V10Algorithm from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "description_short": obj.get("description_short"),
                "organization": obj.get("organization"),
                "category": obj.get("category"),
                "status": obj.get("status"),
                "begin_date": obj.get("begin_date"),
                "end_date": obj.get("end_date"),
                "contact_email": obj.get("contact_email"),
                "website": obj.get("website"),
                "publication_category": obj.get("publication_category"),
                "url": obj.get("url"),
                "goal": obj.get("goal"),
                "proportionality": obj.get("proportionality"),
                "human_intervention": obj.get("human_intervention"),
                "risks": obj.get("risks"),
                "lawful_basis": obj.get("lawful_basis"),
                "lawful_basis_grouping": obj.get("lawful_basis_grouping"),
                "process_index_url": obj.get("process_index_url"),
                "impacttoetsen_grouping": obj.get("impacttoetsen_grouping"),
                "impacttoetsen": obj.get("impacttoetsen"),
                "source_data": obj.get("source_data"),
                "source_data_grouping": obj.get("source_data_grouping"),
                "methods_and_models": obj.get("methods_and_models"),
                "provider": obj.get("provider"),
                "publiccode": obj.get("publiccode"),
                "lang": obj.get("lang"),
                "standard_version": obj.get("standard_version"),
                "source_id": obj.get("source_id"),
                "tags": obj.get("tags"),
                "lars": obj.get("lars"),
                "publication_dt": obj.get("publication_dt"),
                "create_dt": obj.get("create_dt"),
                "language": obj.get("language"),
                "state": obj.get("state"),
            }
        )
        return _obj
