"""make model_card nullable in project

Revision ID: c21dd0bc2c85
Revises: c5254dc6083f
Create Date: 2024-07-17 15:16:15.913247

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c21dd0bc2c85"
down_revision: str | None = "c5254dc6083f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("project", "model_card", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("project", "model_card", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
