INSERT INTO role (id, name) VALUES (1, 'Organization Maintainer');
INSERT INTO role (id, name) VALUES (2, 'Organization Member');
INSERT INTO role (id, name) VALUES (3, 'Organization Viewer');
INSERT INTO role (id, name) VALUES (4, 'Algorithm Maintainer');
INSERT INTO role (id, name) VALUES (5, 'Algorithm Member');
INSERT INTO role (id, name) VALUES (6, 'Algorithm Viewer');
INSERT INTO rule (id, resource, verbs, role_id) VALUES (1, 'organization/{organization_id}', '["Create", "Read", "Update"]', 1);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (2, 'organization/{organization_id}/algorithm', '["List", "Create", "Update", "Delete"]', 1);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (3, 'organization/{organization_id}/member', '["List", "Create", "Update", "Delete"]', 1);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (4, 'organization/{organization_id}', '["Read"]', 2);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (5, 'organization/{organization_id}/algorithm', '["List", "Create"]', 2);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (6, 'organization/{organization_id}/member', '["List"]', 2);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (7, 'organization/{organization_id}', '["Read"]', 3);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (8, 'organization/{organization_id}/algorithm', '["List"]', 3);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (9, 'organization/{organization_id}/member', '["List"]', 3);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (10, 'algorithm/{algorithm_id}', '["Create", "Read", "Delete"]', 4);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (11, 'algorithm/{algorithm_id}/systemcard', '["Read", "Create", "Update"]', 4);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (12, 'algorithm/{algorithm_id}/user', '["Create", "Read", "Update", "Delete"]', 4);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (13, 'algorithm/{algorithm_id}', '["Read", "Create"]', 5);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (14, 'algorithm/{algorithm_id}/systemcard', '["Read", "Create", "Update"]', 5);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (15, 'algorithm/{algorithm_id}/user', '["Read"]', 5);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (16, 'algorithm/{algorithm_id}', '["Read"]', 6);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (17, 'algorithm/{algorithm_id}/systemcard', '["Read"]', 6);
INSERT INTO rule (id, resource, verbs, role_id) VALUES (18, 'algorithm/{algorithm_id}/user', '["Read"]', 6);
