name: Epic
description: Epics describe larger blocks of work (dutch)
labels: ["epic"]
labels: [ ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Epics are written in Dutch as they serve as intermediary with policy.
      placeholder:
      value:
    validations:
      required: true
