- urn: "urn:nl:ak:ver:awb-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-03"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-05"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-7"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-10"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-13"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-22"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-23"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-24"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-25"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-26"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-27"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-28"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-29"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-35"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aia-38"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:arc-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:aut-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-03"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-04"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-05"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-06"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-07"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-08"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-09"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-10"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-11"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-12"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:avg-13"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:awb-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:awb-02"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:bio-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:bzk-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:dat-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:grw-01"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:grw-02"
  state: "to do"
  version: ""
- urn: "urn:nl:ak:ver:woo-01"
  state: "to do"
  version: ""
