# coding: utf-8

# flake8: noqa

"""
Algoritmeregister aanlevering API, versie 1.0

 <h3>⚠️ Belangrijke mededeling</h3> De API versies 0.1.0,  0.4.0 en 1.0.0 worden voortaan verkort naar respectievelijk 0.1, 0.4 en 1.0. <br> Grebruik in de API URLs dus aanleverapi/<b>v0_1</b>, aanleverapi/<b>v0_4</b> en aanleverapi/<b>v1_0</b>.

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ActiesApi",
    "AlgoritmesInOntwikkelingApi",
    "GepubliceerdeAlgoritmesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AlgorithmActionResponse",
    "AlgorithmIn",
    "AlgorithmSummary",
    "AnyOfTheAlgorithmStandards",
    "ArchiveVersionRequest",
    "HTTPValidationError",
    "Language",
    "Message",
    "NewAlgorithmResponse",
    "PreviewUrl",
    "State",
    "V01Algorithm",
    "V01EnumStandardVersion",
    "V023Algorithm",
    "V023EnumDpia",
    "V023EnumIama",
    "V023EnumMprd",
    "V023EnumStandardVersion",
    "V023EnumStatus",
    "V023EnumType",
    "V031Algorithm",
    "V031EnumDpia",
    "V031EnumIama",
    "V031EnumStandardVersion",
    "V031EnumStatus",
    "V031EnumType",
    "V04Algorithm",
    "V04EnumCategory",
    "V04EnumStandardVersion",
    "V04EnumStatus",
    "V04EnumType",
    "V10Algorithm",
    "V10EnumCategory",
    "V10EnumLang",
    "V10EnumPublicationCategory",
    "V10EnumStandardVersion",
    "V10EnumStatus",
    "V10ObjectImpacttoetsenGrouping",
    "V10ObjectLawfulBasisGrouping",
    "V10ObjectSourceDataGrouping",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.api.acties_api import ActiesApi as ActiesApi
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.api.algoritmes_in_ontwikkeling_api import (
    AlgoritmesInOntwikkelingApi as AlgoritmesInOntwikkelingApi,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.api.gepubliceerde_algoritmes_api import (
    GepubliceerdeAlgoritmesApi as GepubliceerdeAlgoritmesApi,
)

# import ApiClient
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.api_response import ApiResponse as ApiResponse
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.api_client import ApiClient as ApiClient
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.configuration import Configuration as Configuration
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.exceptions import OpenApiException as OpenApiException
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.exceptions import ApiTypeError as ApiTypeError
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.exceptions import ApiValueError as ApiValueError
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.exceptions import ApiKeyError as ApiKeyError
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.algorithm_action_response import (
    AlgorithmActionResponse as AlgorithmActionResponse,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.algorithm_in import AlgorithmIn as AlgorithmIn
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.algorithm_summary import (
    AlgorithmSummary as AlgorithmSummary,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.any_of_the_algorithm_standards import (
    AnyOfTheAlgorithmStandards as AnyOfTheAlgorithmStandards,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.archive_version_request import (
    ArchiveVersionRequest as ArchiveVersionRequest,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.http_validation_error import (
    HTTPValidationError as HTTPValidationError,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.language import Language as Language
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.message import Message as Message
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.new_algorithm_response import (
    NewAlgorithmResponse as NewAlgorithmResponse,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.preview_url import PreviewUrl as PreviewUrl
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.state import State as State
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v01_algorithm import V01Algorithm as V01Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v01_enum_standard_version import (
    V01EnumStandardVersion as V01EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_algorithm import (
    V023Algorithm as V023Algorithm,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_dpia import V023EnumDpia as V023EnumDpia
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_iama import V023EnumIama as V023EnumIama
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_mprd import V023EnumMprd as V023EnumMprd
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_standard_version import (
    V023EnumStandardVersion as V023EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_status import (
    V023EnumStatus as V023EnumStatus,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v023_enum_type import V023EnumType as V023EnumType
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_algorithm import (
    V031Algorithm as V031Algorithm,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_dpia import V031EnumDpia as V031EnumDpia
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_iama import V031EnumIama as V031EnumIama
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_standard_version import (
    V031EnumStandardVersion as V031EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_status import (
    V031EnumStatus as V031EnumStatus,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v031_enum_type import V031EnumType as V031EnumType
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_algorithm import V04Algorithm as V04Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_category import (
    V04EnumCategory as V04EnumCategory,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_standard_version import (
    V04EnumStandardVersion as V04EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_status import (
    V04EnumStatus as V04EnumStatus,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v04_enum_type import V04EnumType as V04EnumType
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_algorithm import V10Algorithm as V10Algorithm
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_category import (
    V10EnumCategory as V10EnumCategory,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_lang import V10EnumLang as V10EnumLang
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_publication_category import (
    V10EnumPublicationCategory as V10EnumPublicationCategory,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_standard_version import (
    V10EnumStandardVersion as V10EnumStandardVersion,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_enum_status import (
    V10EnumStatus as V10EnumStatus,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_object_impacttoetsen_grouping import (
    V10ObjectImpacttoetsenGrouping as V10ObjectImpacttoetsenGrouping,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_object_lawful_basis_grouping import (
    V10ObjectLawfulBasisGrouping as V10ObjectLawfulBasisGrouping,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.v10_object_source_data_grouping import (
    V10ObjectSourceDataGrouping as V10ObjectSourceDataGrouping,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.validation_error import (
    ValidationError as ValidationError,
)
from amt.algoritmeregister.openapi.v1_0.client.openapi_client.models.validation_error_loc_inner import (
    ValidationErrorLocInner as ValidationErrorLocInner,
)
