#!/usr/bin/env bash

set -x

# python version manager
if [ python3 -v ]; then
  echo "Python3 is already installed"
else
    echo "Please install python3"
    exit 1
fi

# install python package manager
if [ poetry --version ]; then
    echo "poetry is already installed"
else
    echo "installing poetry"
    pipx install poetry
fi


# node version manager
if [ node -v ]; then
  echo "Node is already installed"
else
  echo "Installing Node"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh
  nvm install
  nvm use
fi

# initialize dependencies for python and node
npm install
poetry install
