#!/usr/bin/env bash

# This script is inteded to be used as a pre-commit hook.
# It checks whether Babel translations are updated and compiled, i.e.
# it will fail when there are translations tags present in the source
# files, but are not present in the .po files.

set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

# pre-commit will fail if files are edited, so we need to create
# a temporary directory, such that we can update to .po files.
TEMP_DIR=$(mktemp -d)
mkdir -p ${TEMP_DIR}/amt/locale
trap 'rm -rf "$TEMP_DIR"' EXIT

print_color() {
    local color_code=$1
    local text=$2
    echo -e "\033[${color_code}m${text}\033[0m"
}

strip_po() {
    tail -n +21 "$1" | awk '{
        if ($1 == "#:") {
            # Remove the last colon and any following digits to ignore changes in just line numbers
            sub(/:[0-9]+$/, "", $0)
        }
        print $0
    }'
}

difference() {
    d=$(diff <(echo "$1") <(echo "$2"))
    if [[ "${d}" != "" ]]; then
        print_color "1;31" "❌ Translations not up to date."
        echo
        print_color "1;33" "Run:"
        echo
        print_color "1;36" "    script/translate update"
        echo
        exit 1
    fi
}

main () {
    en_po="amt/locale/en_US/LC_MESSAGES/messages.po"
    nl_po="amt/locale/nl_NL/LC_MESSAGES/messages.po"

    old_en_po=$(strip_po "${en_po}")
    old_nl_po=$(strip_po "${nl_po}")

    cp -r amt/locale/* ${TEMP_DIR}/amt/locale/
    pybabel extract -F babel-mapping.ini . -o "${TEMP_DIR}/amt/locale/base.pot" > /dev/null 2>&1
    pybabel update -i "${TEMP_DIR}/amt/locale/base.pot" -d "${TEMP_DIR}/amt/locale" > /dev/null 2>&1

    new_en_po=$(strip_po ${TEMP_DIR}/"${en_po}")
    new_nl_po=$(strip_po ${TEMP_DIR}/"${nl_po}")

    difference "${old_en_po}" "${new_en_po}"
    difference "${old_nl_po}" "${new_nl_po}"

    ./script/check_invalid_translations --filenames "${nl_po}"
}

main
