#!/usr/bin/env bash

set -e
set -x

coverage run -m pytest $@
if [ $? -ne 0 ]; then
    echo "Test failed"
    exit 1
fi

coverage report
coverage html
coverage lcov
pyright $@
if [ $? -ne 0 ]; then
    echo "Typecheck failed"
    exit 1
fi
