#!/usr/bin/env bash

set -e
set -x


if ! poetry run coverage run -m pytest "$@" ; then
    echo "pytest test failed"
    exit 1
fi

if ! npm run test ; then
    echo "jest test failed"
    exit 1
fi


coverage report
coverage html
coverage lcov

if ! pyright; then
    echo "Typecheck failed"
    exit 1
fi
