#!/usr/bin/env bash

set -e
set -x


if ! poetry run coverage run -m pytest "$@" ; then
    echo "Test failed"
    exit 1
fi

coverage report
coverage html
coverage lcov

if ! pyright; then
    echo "Typecheck failed"
    exit 1
fi
