#!/usr/bin/env bash

if [ "$#" -ne 1 ]
then

    echo "Usage: ./translate command"
    echo "command is init (caution: only needed once, it creates empty translation files), update, compile"
    exit 1
fi

if [ "$1" = "compile" ]
then
    pybabel compile -d amt/locale
elif [ "$1" = "init" ]
then
    pybabel extract -F babel-mapping.ini . -o amt/locale/base.pot
    pybabel init -l en_US -i amt/locale/base.pot -d amt/locale
    pybabel init -l nl_NL -i amt/locale/base.pot -d amt/locale
    pybabel init -l nl_FY -i amt/locale/base.pot -d amt/locale
elif [ "$1" = "update" ]
then
    pybabel extract -F babel-mapping.ini . -o amt/locale/base.pot
    pybabel update -i amt/locale/base.pot -d amt/locale
else
    echo "Unknown command"
    exit 1
fi
