name: pr-close

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number'
        required: true
        type: string

jobs:
  cleanup-package-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        if: ${{ github.event_name != 'pull_request' }}
        with:
          package-name: 'tad'
          package-type: 'container'
          package-version-ids: ${{ inputs.pr_number }}

      - uses: actions/delete-package-versions@v5
        if: ${{ github.event_name == 'pull_request' }}
        with:
          package-name: 'tad'
          package-type: 'container'
          package-version-ids: PR-${{ github.event.number }}
